### ISSUE TITLE
Animated WebP not being played

### ISSUE THREAD

**Issue by nianxiongdi** [dream-sports-labs/react-native-fast-image#125]
[bug link](https://github.com/DylanVann/react-native-fast-image/issues/1055)

**Comment by princektripathi** [comment]
> [bug link](https://github.com/DylanVann/react-native-fast-image/issues/1055)

@nianxiongdi, thank you for bringing this issue to our attention. We will look into it and get back to you.

**Comment by deepanshushukla** [comment]
@princektripathi Any update  on the  fix
