### ISSUE TITLE
Cannot inherit from final ImageSource

### ISSUE THREAD

**Issue by yousefArb** [dream-sports-labs/react-native-fast-image#13]
**Hi**

Now in **react native 0.75.0.rc-6** `ImageSource` class is final class which cannot be inherited, so I cannot use **react-native-fast-image** with my project.

could you fix this issue, if yes when can it be done?

thanks

**Comment by AndrewMatsiuk** [comment]
Hi, your project in Android works correctly, where do you use FastImage ?

**Comment by yousefArb** [comment]
No it's not working, Build failed because of **Cannot inherit from final ImageSource** error

**Comment by AndrewMatsiuk** [comment]
> No it's not working, Build failed because of **Cannot inherit from final ImageSource** error

I understand, I have a completely different error 😃 . From what I've gathered, this library doesn't work on newer versions of React Native; iOS works, but Android doesn't work at all.

**Comment by deepanshushuklad11** [comment]
@yousefArb I will look in to it for sure . Give me some time i will share the timelines

**Comment by YuriOlepir** [comment]
Hello, after updating the react-native to  `0.75.0.rc-7` I have the same error during the run `yarn android `

**Comment by YuriOlepir** [comment]
link to the issue in the original repo https://github.com/DylanVann/react-native-fast-image/issues/1043

**Comment by deepanshushukla** [comment]
@yousefArb I will be picking this up

**Comment by deepanshushuklad11** [comment]
@YuriOlepir @yousefArb I will be picking this up

**Comment by deepanshushuklad11** [comment]
@YuriOlepir @yousefArb https://github.com/facebook/react-native/pull/46092
Meta has changed the class , now its open for inheritance , in newer release this will be fixed automatically

**Comment by Pratik-2102** [comment]
@deepanshushuklad11 
Thank you for breathing new life into the old library by fixing issues and adding support for the latest React Native versions—your efforts are truly appreciated!

**Comment by Kolahzary** [comment]
It's not fixed in the newest version: ```"react-native": "0.75.2",```

**Comment by deepanshushuklad11** [comment]
> It's not fixed in the newest version: `"react-native": "0.75.2",`

I think there was a miss in the PR by a new PR has been raised to fix https://github.com/facebook/react-native/pull/46152.
