### ISSUE TITLE
View manager resolver returned null for either FastImageView or RCTImageView, existing names are: etc...

### ISSUE THREAD

**Issue by ivor-19** [dream-sports-labs/react-native-fast-image#130]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:

**Expected behavior**

**Screenshots**

**Dependency versions**

- React Native version:
- React version:
- React Native Fast Image version:

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by mayankkush1** [comment]
Hey @ivor-19. Please share more description about the issue.
- Reproducer
- Expected behaviour
- Library version
- React native version
- Error logs

**Comment by princektripathi** [comment]
@ivor-19, closing this issue due to missing debug information. Feel free to open it with reproducer if the issue persists.

**Comment by Akash-Pavithran** [comment]
@princektripathi This issue happens in a any latest project created through expo. I tried installing this package in a brand new RN project created through expo
![Screenshot_1736700184](https://github.com/user-attachments/assets/f06f04c6-04c4-41a1-8300-11b5bc765d73)

`"react": "18.3.1",
    "react-native": "0.76.6",
    "@d11/react-native-fast-image": "^8.9.1",`

**Comment by princektripathi** [comment]
@Akash-Pavithran, can you please share a sample reproducer for the validation? I'll re-open this issue if validated.

**Comment by Akash-Pavithran** [comment]
Hi @princektripathi I've pushed the sample project repo https://github.com/Akash-Pavithran/view-manager-resolver-fastimage-reprod

**Comment by Akash-Pavithran** [comment]
@princektripathi any updates about this issue?

**Comment by princektripathi** [comment]
> Hi [@princektripathi](https://github.com/princektripathi) I've pushed the sample project repo https://github.com/Akash-Pavithran/view-manager-resolver-fastimage-reprod

@Akash-Pavithran, I'll check it today and get back to you.

**Comment by princektripathi** [comment]
@Akash-Pavithran, I validated in a sample Expo project with following versions and it works as expected -
 
```
    "expo": "~52.0.28",
    "react": "18.3.1",
    "react-native": "0.76.6" 
```

Please ensure that you run `expo prebuild --clean` once you have added our package in an Expo project. [ref](https://docs.expo.dev/workflow/continuous-native-generation/)

**Comment by Akash-Pavithran** [comment]
Thanks @princektripathi  will try with `"expo": "~52.0.28",`
