### ISSUE TITLE
Value for headers cannot be cast from ReadableNativeArray to ReadableNativeMap

### ISSUE THREAD

**Issue by pardeep-kumar94** [dream-sports-labs/react-native-fast-image#134]
**Describe the bug**

On Passing headers to throws  **Value for headers cannot be cast from ReadableNativeArray to ReadableNativeMap**

<FastImage
      style={imgStyle}
      source={{
            uri: imageUri,
            priority: FastImage.priority.high,
            cache: FastImage.cacheControl.immutable,
            headers: {
              Authorization: "<token>"
            },
          }}
      resizeMode={FastImage.resizeMode.contain}
    />

**Dependency versions**

- React Native version: 0.74.4
- React version: 18.2.0
- React Native Fast Image version:  8.8.1
- NewArchEnabled = true

**Comment by pardeep-kumar94** [comment]
@deepanshushuklad11  help needed here

**Comment by pardeep-kumar94** [comment]
So i figured out this issue. 
On new architecture while uploading the headers, its being added to the array. not in hashmap. 

![Screenshot 2024-11-26 at 3 27 18 PM](https://github.com/user-attachments/assets/9a954225-8ee4-4ad5-a1b3-c1e98af421cb)


but while extracting these headers , its trying to extract from object. Ideally it should be an extract from array element. 
![Screenshot 2024-11-26 at 3 28 50 PM](https://github.com/user-attachments/assets/546d898b-8961-4480-ba21-f8ecd84daf94)


As this issue is resolved for me. I am closing this issue. But Let me know if a pull-request is required for this one. I am happy to share

**Comment by Anb98** [comment]
> Hey @pardeep-kumar94 - How did you resolve this issue? I noticed I had the same issue on Android with this library and didn't see any releases to the package which resolved the problem.
> 
> If you know a fix on the native-level code, are you able to submit a PR to the repository to be included in the next release? It would be really helpful, thank you!
> 
> Edit: I should clarify that I'm experiencing this issue on _the old architecture_

@sam-at-zoe I've developed a fix that works for me on the old architecture, which might help you as well, check the PR: https://github.com/dream-sports-labs/react-native-fast-image/pull/148
