### ISSUE TITLE
[Android / RN 0.73.9] error: cannot find symbol getReactApplicationContext()

### ISSUE THREAD

**Issue by adammcarth** [dream-sports-labs/react-native-fast-image#21]
**Describe the bug**
Android Studio throws and error when compiling the app in debug mode using React Native 0.73.9:

```text
/.../node_modules/@d11/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewManager.java:125: error: cannot find symbol
                ReactContext context = getReactApplicationContext();
                                       ^
  symbol:   method getReactApplicationContext()
  location: class FastImageViewManager
```

**To Reproduce**
1. `npx react-native@0.73.9 init AwesomeProject --version 0.73.9`
2. `yarn add @d11/react-native-fast-image`
3. Open project in Android studio and try to build the app

**Expected behavior**
The app to compile without any errors.

**Dependency versions**

- React Native version: `0.73.9`
- React version: `18.2.0`
- React Native Fast Image version: `^8.6.9`

**Comment by adammcarth** [comment]
May be related to #13 or supporting Android more broadly.

**Comment by deepanshushuklad11** [comment]
@adammcarth can you try the nightly build
