### ISSUE TITLE
Crashes with  you must return a valid, non-null value from `getEventData`, or override `dispatch` and `dispatchModern`. Event: onFastImageLoadStart

### ISSUE THREAD

**Issue by giantslogik** [dream-sports-labs/react-native-fast-image#36]
**Describe the bug**

Event: you must return a valid, non-null value from `getEventData`, or override `dispatch` and `dispatchModern`. Event: onFastImageLoadStart

com.facebook.react.uimanager.events.d in dispatch at line 42
com.swmansion.reanimated.NodesManager in handleEvent at line 1
com.swmansion.reanimated.NodesManager in onEventDispatch at line 12
com.facebook.react.uimanager.events.f in c at line 28
com.dylanvann.fastimage.c in e at line 248
com.dylanvann.fastimage.FastImageViewManager in onAfterUpdateTransaction at line 3

**To Reproduce**
I switched to use this fork  from https://github.com/DylanVann/react-native-fast-image

**Expected behavior**
Does not crash

**Screenshots**

**Dependency versions**

- React Native version: 0.73.6
- React version: 18.2.0
- React Native Fast Image version: release-v8.6.10

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by deepanshushukla** [comment]
@giantslogik This comes in debug mode and prod both.
and can you elaborate more with screenshots or video.

**Comment by deepanshushuklad11** [comment]
@giantslogik does this comes in debug mode and prod both.
and can you elaborate more with screenshots or video.

**Comment by deepanshushuklad11** [comment]
@giantslogik Found the issue . Will fix

**Comment by giantslogik** [comment]
@deepanshushuklad11 thanks ! Happy to find a maintained fork of this excellent library. Will try and PR anything i can fix/improve. Did you do any work on the Android Preloading? I'm trying to determine the cause of https://github.com/DylanVann/react-native-fast-image/issues/657 .

**Comment by deepanshushuklad11** [comment]
> @deepanshushuklad11 thanks ! Happy to find a maintained fork of this excellent library. Will try and PR anything i can fix/improve. Did you do any work on the Android Preloading? I'm trying to determine the cause of [DylanVann/react-native-fast-image#657](https://github.com/DylanVann/react-native-fast-image/issues/657) .

You are saying preloading doesn't work on android ?

**Comment by deepanshushuklad11** [comment]
@giantslogik I checked the issue its related to getEventData should be overridden and return empty object instead of null.
Since this is working on newer version of react-native i am not prioritising this at this moment.
I will be working on  fabric support  so i will take care of this in the same .
If you are blocked on this i can suggest you a patch if needed

**Comment by giantslogik** [comment]
@deepanshushuklad11  I'm back to using the original branch with a patch i wrote for android preloading: https://github.com/DylanVann/react-native-fast-image/issues/657#issuecomment-2312378889 . Will try this fork after i upgrade RN.
