### ISSUE TITLE
Task :d11_react-native-fast-image:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by nicolaturcoep** [dream-sports-labs/react-native-fast-image#39]
after command "npm run android"

> Task :d11_react-native-fast-image:compileDebugJavaWithJavac FAILED
note: generating mipmap/ic_launcher_round with config "ldpi-v26" for round icon compatibility.                                                                                            
note: generating mipmap/ic_launcher_round with config "mdpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_round with config "hdpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_round with config "xhdpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_round with config "xxhdpi-v26" for round icon compatibility.
note: generating mipmap/ic_launcher_round with config "xxxhdpi-v26" for round icon compatibility.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

**Comment by deepanshushuklad11** [comment]
@nicolaturcoep Can you help me more details or a  minimum reproducer would be nice

**Comment by nicolaturcoep** [comment]
original error was: Task :react-native-fast-image:compileDebugJavaWithJavac

I tried the package as recommended in this thread: https://github.com/DylanVann/react-native-fast-image/issues/1009
but it doesn't solve

my configuration:
"react": "18.3.1",
"react-native": "0.75.2",
"react-native-fast-image": "^8.6.3",

java: openjdk version "17.0.10" 2024-01-16 LTS
gradle: 8.10
node: 21.7.3
npm: 10.8.2

**Comment by deepanshushuklad11** [comment]
@nicolaturcoep you have used original [react-native-fast-image](https://www.npmjs.com/package/react-native-fast-image) which is not maintained anymore
you should try [@d11/react-native-fast-image](https://www.npmjs.com/package/@d11/react-native-fast-image) this is a fork of original repo currently maintained by dream-sports-labs.
We are working on fabric support where we will increase the AGP version , you can track the [PR](https://github.com/dream-sports-labs/react-native-fast-image/pull/37) here.

**Comment by SebiVPS** [comment]
I also get this error: 

`Task :d11_react-native-fast-image:compileDebugJavaWithJavac FAILED`

Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]

/Users/.../node_modules/@d11/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:72: error: isResource() in FastImageSource cannot override isResource() in ImageSource
    public boolean isResource() {
                   ^
  overridden method is final
/Users/.../node_modules/@d11/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:101: error: getUri() in FastImageSource cannot override getUri() in ImageSource
    public Uri getUri() {
               ^
  overridden method is final
2 errors

___

I updated my project from react-native v0.73.9 to v0.75.2.
I used the original package, where this forked repo comes from before and update to your version but i get the same error in both versions.  
Maybe you have an idea whats the problem here?
Thank you for trying to keep this project alive!

**Comment by deepanshushuklad11** [comment]
> I also get this error:
> 
> `Task :d11_react-native-fast-image:compileDebugJavaWithJavac FAILED`
> 
> Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
> 
> /Users/.../node_modules/@d11/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:72: error: isResource() in FastImageSource cannot override isResource() in ImageSource public boolean isResource() { ^ overridden method is final /Users/.../node_modules/@d11/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:101: error: getUri() in FastImageSource cannot override getUri() in ImageSource public Uri getUri() { ^ overridden method is final 2 errors
> 
> I updated my project from react-native v0.73.9 to v0.75.2. I used the original package, where this forked repo comes from before and update to your version but i get the same error in both versions. Maybe you have an idea whats the problem here? Thank you for trying to keep this project alive!
> 
> Edit: Also mentioned here: [DylanVann/react-native-fast-image#1048](https://github.com/DylanVann/react-native-fast-image/issues/1048) Just saw that there already exists a fix for this issue, maybe you can use that? [DylanVann/react-native-fast-image#1045](https://github.com/DylanVann/react-native-fast-image/issues/1045)

I wanted to fix this issue , but react-native team already fixed this ,  which will be released in next version after 0.75.2.
So i am waiting for that

**Comment by deepanshushuklad11** [comment]
@SebiVPS I would suggest you to try [react-native-nightly](https://www.npmjs.com/package/react-native/v/0.76.0-nightly-20240908-d687d3898)

**Comment by deepanshushuklad11** [comment]
@SebiVPS I will fix this  within a day or two

**Comment by SebiVPS** [comment]
@deepanshushuklad11 Great! Thanks a lot!

**Comment by deepanshushuklad11** [comment]
@SebiVPS This is fixed , and i have published a new version

**Comment by SebiVPS** [comment]
Thank you very much 🙌
