### ISSUE TITLE
Add library to React Native Directory

### ISSUE THREAD

**Issue by muhammedyasirmt** [dream-sports-labs/react-native-fast-image#40]
It would be helpful for users searching for appropriate library to have this library in React Native Directory.

link to React Native Directory 
https://reactnative.directory/

link to How to add
https://github.com/react-native-community/directory/?tab=readme-ov-file#how-do-i-add-a-library

**Comment by deepanshushuklad11** [comment]
@muhammedyasirmt Sure will check

**Comment by shubh73** [comment]
done https://github.com/react-native-community/directory/pull/1301

**Comment by deepanshushuklad11** [comment]
> done [react-native-community/directory#1301](https://github.com/react-native-community/directory/pull/1301)

@shubh73 Thanks.  Some checks are failing can you check your PR again

**Comment by shubh73** [comment]
Yes, the CI seems to be [failing](https://github.com/react-native-community/directory/actions/runs/11149032795/job/30986971719) because the fork is considered as a duplicate library. I'll get in touch with the maintainer to fix this by tomorrow.

**Comment by shubh73** [comment]
@deepanshushuklad11 the PR has been merged.

**Comment by deepanshushuklad11** [comment]
@shubh73 Thanks . I am closing this issue
