### ISSUE TITLE
Request to add getCachePath function

### ISSUE THREAD

**Issue by derekchan916** [dream-sports-labs/react-native-fast-image#42]
If possible, could this patch be applied so that we can expose `getCachePach`? https://github.com/phantom/react-native-fast-image/commit/5c17f44c7f600ab197a0c5756edcb28ed1d5e44b

Thanks for keeping this package up to date.

**Comment by deepanshushuklad11** [comment]
@derekchan916 Can you raise the PR , I will look in to it
