### ISSUE TITLE
Local Images not showing on debug and production builds android 

### ISSUE THREAD

**Issue by bestoferanda** [dream-sports-labs/react-native-fast-image#76]
**Describe the bug**
Local Images not showing on debug and production builds android 

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:
When production build or debug build is created. apk - images not showing on fast image. 
when we use react native default image component they are showing 
remote server images but loading all ok

**Expected behavior**
Images should load

**Screenshots**
N/A

**Dependency versions**

- React Native version:0.74.5
- React version:18.2.0
- React Native Fast Image version:8.6.12
**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by deepanshushuklad11** [comment]
@bestoferanda Can you show me the code, how you are loading the image , a small reproducer would be of great help

**Comment by bestoferanda** [comment]
> @bestoferanda Can you show me the code, how you are loading the image , a small reproducer would be of great help

` const LOGIN_HEADER_IMAGE = require('./login_header.jpeg');

//Showing
      <View style={styles.container}>
        <Image
          source={Images.LOGIN_HEADER_IMAGE}
          style={styles.headerImage}
          resizeMode="cover"
        />
      </View>
      
      //Image component
            <FastImage
        style={imageStyle}
        source={source}
        resizeMode={resizeMode || FastImage.resizeMode.contain}
        onLoadStart={() => {
          !loading && setLoading(true);
        }}
        onError={() => {
          loading && setLoading(false);
        }}
        onLoadEnd={() => {
          loading && setLoading(false);
        }}
        {...rest}>
        {children}
      </FastImage>
`

Note - This is working fine when app is running on emulator or directly on device. but its is not working after we created apk file on android either debug or release build

**Comment by deepanshushuklad11** [comment]
@bestoferanda Just Tested on debug builds its working fine , React native version is 75.2

**Comment by zenox69** [comment]
Same problem here, local images wont load of production/release builds

**Comment by deepanshushuklad11** [comment]
@zenox69 @bestoferanda Can you please provide a simple reproducer app on GitHub.
