### ISSUE TITLE
If possible, please make FastImage.preload() return Promise.

### ISSUE THREAD

**Issue by HarwinderSingh15** [dream-sports-labs/react-native-fast-image#9]
Hi Guys,

First of all, You are doing awesome work. Package was almost abandoned. Thanks for reviving it.

Secondly, I have a situation where I need to preload the image (5-6) before showing to the user. I have used ReactNative's Image component for caching bcs it's Image.preload returns promise and fast image  was not actively maintained. But now I'm using your forked repo. 

Can you please make ```FastImage.preload()``` promise.

Thanks

**Comment by deepanshushuklad11** [comment]
@HarwinderSingh15 Can you explain more about your use-case or share some code if possible.

**Comment by HarwinderSingh15** [comment]
@deepanshushuklad11 

👇Here is my use case 

I need to preload all the images for the screen before navigating to it, similar to how Instagram does. I show a loading indicator until all the images are loaded, and then I display the screen. Previously, I achieved this using `Image.preload` provided by React Native, which returns a promise. Now that I'm using the FastImage package, the `FastImage.preload()` method does not return a promise.

**Comment by deepanshushuklad11** [comment]
@HarwinderSingh15 this seems very specific use case , ideally user should move on to next screen and preload can happen in background.

**Comment by HarwinderSingh15** [comment]
@deepanshushuklad11
I agree with you, but making it promise can help in both situation

**Comment by deepanshushuklad11** [comment]
@HarwinderSingh15 Fair point.
If you could make changes and raise a PR for the same i am happy to look.

**Comment by HarwinderSingh15** [comment]
@deepanshushuklad11 Sure. I'll create PR within some days. Thanks
