### ISSUE TITLE
Build failed on android

### ISSUE THREAD

**Issue by bestoferanda** [dream-sports-labs/react-native-fast-image#90]
**Describe the bug**
building failed on android

`Execution failed for task ':d11_react-native-fast-image:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 14s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/oldarch/java/com/FastImageViewManager.java:36: error: duplicate class: com.dylanvann.fastimage.FastImageViewManager
class FastImageViewManager extends SimpleViewManager<FastImageViewWithUrl> implements FastImageProgressListener {
^
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:29: error: cannot find symbol
import com.facebook.react.viewmanagers.FastImageViewManagerDelegate; ^ symbol: class FastImageViewManagerDelegate location: package com.facebook.react.viewmanagers
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:30: error: cannot find symbol
import com.facebook.react.viewmanagers.FastImageViewManagerInterface; ^ symbol: class FastImageViewManagerInterface location: package com.facebook.react.viewmanagers
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:39: error: cannot find symbol
class FastImageViewManager extends SimpleViewManager<FastImageViewWithUrl> implements FastImageProgressListener, FastImageViewManagerInterface<FastImageViewWithUrl> { ^ symbol: class FastImageViewManagerInterface
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:58: error: cannot find symbol mDelegate = new FastImageViewManagerDelegate<>(this); ^ symbol: class FastImageViewManagerDelegate location: class FastImageViewManager
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:75: error: method does not override or implement a method from a supertype @Override ^
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:80: error: method does not override or implement a method from a supertype @Override ^
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:87: error: method does not override or implement a method from a supertype @Override ^
/Users/erandamahaliyanage/Documents/GitHub/reTraceMobile/node_modules/@d11/react-native-fast-image/android/src/newarch/java/com/FastImageViewManager.java:96: error: method does not override or implement a method from a supertype @Override ^
9 errors FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':d11_react-native-fast-image:compileDebugJavaWithJavac'.`

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:
1.install the library 
2. run react native project

**Expected behavior**
should work all ok

**Screenshots**

**Dependency versions**

- React Native version:0.74.5
- React version:18.2.0
- React Native Fast Image version: 8.7.0

**Comment by deepanshushuklad11** [comment]
@bestoferanda  can you help me with a reproducer , i recently checked , library was working well

**Comment by bestoferanda** [comment]
> @bestoferanda can you help me with a reproducer , i recently checked , library was working well

This is the same issue mentioned here
https://github.com/DylanVann/react-native-fast-image/issues/1048#issuecomment-2340213127

**Comment by deepanshushuklad11** [comment]
@bestoferanda This issue has been fixed and verified  by others . Can you clean your project and try again

**Comment by bestoferanda** [comment]
> * 8.7.0

already tried with cache clean but not working 
version 8.7.0 has the issue and version 8.6.12 working fine

**Comment by bestoferanda** [comment]
> @bestoferanda This issue has been fixed and verified by others . Can you clean your project and try again

already tried with cache clean but not working
version 8.7.0 has the issue and version 8.6.12 working fine

**Comment by deepanshushuklad11** [comment]
Ok , Thats interesting , I have added support for fabric renderer in 8.7.0 .
Did you try on a fresh sample app ?

**Comment by deepanshushuklad11** [comment]
@bestoferanda I just tested on 8.7.0 new arch and old arch , both are working as expected.
